{% set name = "abipy" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4aef7f5467f9f9f0694b9b0877d56159e0d04b2957fa47fc9412d3dd8c837b74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - monty
    - tabulate
    - apscheduler
    - pydispatcher >=2.0.5
    - tqdm
    - pyyaml >=3.11
    - pandas
    - numpy
    - scipy
    - sympy
    - spglib
    - pymatgen >=2019.12.22
    - netcdf4
    - matplotlib-base
    - seaborn

test:
  imports:
    - abipy

about:
  home: http://abinit.github.io/abipy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Open-source library for analyzing the results produced by ABINIT

  description: |
    AbiPy is a Python library to analyze the results produced by 
    Abinit, an open-source program for the ab-initio calculations 
    of the physical properties of materials within Density Functional 
    Theory and Many-Body perturbation theory. It also provides tools 
    to generate input files and workflows to automate ab-initio 
    calculations and typical convergence studies. AbiPy is 
    interfaced with pymatgen and this allows users to benefit from 
    the different tools and python objects available in the pymatgen 
    ecosystem.
  doc_url: http://abinit.github.io/abipy
  dev_url: https://github.com/abinit/abipy

extra:
  recipe-maintainers:
    - jan-janssen
    - gmatteo
