{% set name = "abipy" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d55599b2b8a8ae44910066a37a8fad67c0d076d104ad46059ab96c7d5f8351da

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - monty
    - tabulate
    - apscheduler <=3.10.4
    - pydispatcher >=2.0.5
    - tqdm
    - pyyaml >=3.11
    - ruamel.yaml >=0.16.12
    - pandas
    - numpy <2.0.0
    - scipy
    - sympy
    - spglib
    - pymatgen >=2023.3.23
    - netcdf4
    - matplotlib-base
    - seaborn
    - plotly
    - ipython
    - chart-studio
    - click
    - ase
    - phonopy

test:
  imports:
    - abipy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://abinit.github.io/abipy
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Open-source library for analyzing the results produced by ABINIT

  description: |
    AbiPy is a Python library to analyze the results produced by
    Abinit, an open-source program for the ab-initio calculations
    of the physical properties of materials within Density Functional
    Theory and Many-Body perturbation theory. It also provides tools
    to generate input files and workflows to automate ab-initio
    calculations and typical convergence studies. AbiPy is
    interfaced with pymatgen and this allows users to benefit from
    the different tools and python objects available in the pymatgen
    ecosystem.
  doc_url: http://abinit.github.io/abipy
  dev_url: https://github.com/abinit/abipy

extra:
  recipe-maintainers:
    - jan-janssen
    - gmatteo
